default:
  image: python:3.9
  before_script:
    - apt-get update
    - apt-get install -y util-linux binutils coreutils pylint lsb-release python3-sphinx dvipng imagemagick-6.q16 latexmk sphinx-doc libjs-mathjax texlive-fonts-recommended texlive-latex-base texlive-latex-recommended texlive-latex-extra xzdec
    - python --version
    - lsb_release -a

stages:
    - Static Analysis
    - Doc Generation

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - ls -l
    - for file in `find . -iname "*.py"`; do pylint $file; done

sphinx:
  stage: Doc Generation
  script:
    - cd docs
    - make html
    - make epub
    - make latexpdf